name: Rust Crate Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build and test
        env:
          WEBWARE_URL: ${{ secrets.WEBWARE_URL }}
          VENDOR_HASH: ${{ secrets.VENDOR_HASH }}
          APP_HASH: ${{ secrets.APP_HASH }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REVISION: ${{ secrets.REVISION }}
        run: |
          cargo build --verbose
          cargo test --verbose
